import { Merchant, Product, User } from './types'

// Mock Users
export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'Budi Santoso',
    email: 'budi@example.com',
    phone: '081234567890',
    password: 'password123',
  },
  {
    id: '2',
    name: 'Siti Nurhaliza',
    email: 'siti@example.com',
    phone: '082234567890',
    password: 'password123',
  },
]

// Mock Merchants
export const MOCK_MERCHANTS: Merchant[] = [
  {
    id: 'mcd',
    slug: 'mcdonalds',
    name: "McDonald's Indonesia",
    description: 'Restoran makanan cepat saji terpercaya dengan menu burger dan chicken favorit sejak 1980',
    logo: 'https://placehold.co/120x120/FFD700/000000?text=McD',
    heroImage: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=1920&q=80',
    category: 'Fast Food',
    pointsMultiplier: 0.5,
    featured: true,
  },
  {
    id: 'starbucks',
    slug: 'starbucks',
    name: 'Starbucks Coffee',
    description: 'Kopi premium dan minuman segar dari kafe terbaik dunia dengan suasana nyaman',
    logo: 'https://placehold.co/120x120/00704A/FFFFFF?text=SBX',
    heroImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1920&q=80',
    category: 'Café',
    pointsMultiplier: 1,
    featured: true,
  },
  {
    id: 'indomaret',
    slug: 'indomaret',
    name: 'Indomaret Convenience',
    description: 'Toko swalayan modern dengan berbagai produk kebutuhan sehari-hari terlengkap',
    logo: 'https://placehold.co/120x120/D32F2F/FFFFFF?text=IDM',
    heroImage: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?auto=format&fit=crop&w=1920&q=80',
    category: 'Retail',
    pointsMultiplier: 0.2,
    featured: false,
  },
]

// Mock Products
export const MOCK_PRODUCTS: Product[] = [
  // McDonald's Products
  {
    id: 'mcd-1',
    merchantId: 'mcd',
    name: 'Big Mac Combo',
    description: 'Burger legendaris dengan daging sapi berkualitas dan sayuran segar, lengkap dengan fries dan minuman',
    price: 75000,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    category: 'Burger',
    rating: 4.8,
    sold: 1240,
  },
  {
    id: 'mcd-2',
    merchantId: 'mcd',
    name: 'Fried Chicken Deluxe',
    description: "Ayam goreng renyah dengan bumbu rahasia McDonald's yang terkenal",
    price: 65000,
    image: 'https://images.unsplash.com/photo-1562802378-173fd0dae63b?auto=format&fit=crop&w=600&q=80',
    category: 'Chicken',
    rating: 4.7,
    sold: 980,
  },
  {
    id: 'mcd-3',
    merchantId: 'mcd',
    name: 'French Fries',
    description: 'Kentang goreng gurih dan renyah, sempurna sebagai pendamping burger',
    price: 25000,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    category: 'Side',
    rating: 4.6,
    sold: 2150,
  },
  {
    id: 'mcd-4',
    merchantId: 'mcd',
    name: 'Soft Drink Combo',
    description: 'Minuman segar dalam berbagai pilihan rasa, ukuran besar',
    price: 20000,
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80',
    category: 'Drinks',
    rating: 4.5,
    sold: 3200,
  },
  {
    id: 'mcd-5',
    merchantId: 'mcd',
    name: 'McSpicy Burger',
    description: 'Burger spicy dengan daging ayam crispy dan saus pedas nikmat',
    price: 55000,
    image: 'https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=600&q=80',
    category: 'Burger',
    rating: 4.6,
    sold: 750,
  },
  {
    id: 'mcd-6',
    merchantId: 'mcd',
    name: 'Apple Pie',
    description: 'Dessert manis dengan isi apel segar dan renyah di luar',
    price: 15000,
    image: 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?auto=format&fit=crop&w=600&q=80',
    category: 'Dessert',
    rating: 4.4,
    sold: 890,
  },

  // Starbucks Products
  {
    id: 'sb-1',
    merchantId: 'starbucks',
    name: 'Caramel Macchiato',
    description: 'Espresso dengan vanila dan karamel, dinikmati dengan susu lembut',
    price: 55000,
    image: 'https://images.unsplash.com/photo-1485808191679-5f86510bd9d5?auto=format&fit=crop&w=600&q=80',
    category: 'Coffee',
    rating: 4.9,
    sold: 2100,
  },
  {
    id: 'sb-2',
    merchantId: 'starbucks',
    name: 'Iced Latte',
    description: 'Kopi latte dingin dengan susu segar untuk kesegaran maksimal',
    price: 50000,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=600&q=80',
    category: 'Coffee',
    rating: 4.8,
    sold: 1950,
  },
  {
    id: 'sb-3',
    merchantId: 'starbucks',
    name: 'Matcha Latte',
    description: 'Minuman matcha premium yang menyegarkan dengan tekstur lembut',
    price: 60000,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99eb4b174?auto=format&fit=crop&w=600&q=80',
    category: 'Specialty',
    rating: 4.7,
    sold: 1320,
  },
  {
    id: 'sb-4',
    merchantId: 'starbucks',
    name: 'Chocolate Croissant',
    description: 'Pastry lezat dengan cokelat premium, hangat dan nikmat',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1555507036-ab794f4afe5e?auto=format&fit=crop&w=600&q=80',
    category: 'Pastry',
    rating: 4.6,
    sold: 1680,
  },
  {
    id: 'sb-5',
    merchantId: 'starbucks',
    name: 'Espresso Doppio',
    description: 'Double shot espresso untuk pecinta kopi sejati',
    price: 40000,
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=600&q=80',
    category: 'Coffee',
    rating: 4.8,
    sold: 920,
  },
  {
    id: 'sb-6',
    merchantId: 'starbucks',
    name: 'Vanilla Bean Frappuccino',
    description: 'Minuman sejuk yang creamy dengan vanilla premium',
    price: 58000,
    image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?auto=format&fit=crop&w=600&q=80',
    category: 'Specialty',
    rating: 4.9,
    sold: 1540,
  },

  // Indomaret Products
  {
    id: 'indo-1',
    merchantId: 'indomaret',
    name: 'Indomie Goreng Spesial',
    description: 'Mie instan goreng dengan cita rasa autentik Indonesia',
    price: 5000,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
    category: 'Food',
    rating: 4.5,
    sold: 5200,
  },
  {
    id: 'indo-2',
    merchantId: 'indomaret',
    name: 'Aqua Botol 600ml',
    description: 'Air minum bersih dan sehat untuk kebutuhan sehari-hari',
    price: 8000,
    image: 'https://images.unsplash.com/photo-1548032885-b5e38734688a?auto=format&fit=crop&w=600&q=80',
    category: 'Drinks',
    rating: 4.7,
    sold: 8900,
  },
  {
    id: 'indo-3',
    merchantId: 'indomaret',
    name: 'Snack Chitato Original',
    description: 'Keripik kentang renyah dengan rasa original yang lezat',
    price: 15000,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80',
    category: 'Snacks',
    rating: 4.6,
    sold: 4100,
  },
  {
    id: 'indo-4',
    merchantId: 'indomaret',
    name: 'Tissue Premium 250 sheet',
    description: 'Tissue lembut dan berkualitas untuk penggunaan rumah tangga',
    price: 12000,
    image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=600&q=80',
    category: 'Household',
    rating: 4.4,
    sold: 3450,
  },
  {
    id: 'indo-5',
    merchantId: 'indomaret',
    name: 'Minuman Soda Lemon',
    description: 'Minuman soda lemon segar dengan rasa yang nikmat',
    price: 10000,
    image: 'https://images.unsplash.com/photo-1559839914-17aae19cec71?auto=format&fit=crop&w=600&q=80',
    category: 'Drinks',
    rating: 4.5,
    sold: 6700,
  },
  {
    id: 'indo-6',
    merchantId: 'indomaret',
    name: 'Kue Spesial Bundle',
    description: 'Paket kue spesial untuk perayaan dengan berbagai varian',
    price: 50000,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
    category: 'Food',
    rating: 4.8,
    sold: 1200,
  },
]

// Mock User Points Data
export const MOCK_USER_POINTS_DATA = {
  totalPoints: 1250,
  availablePoints: 1250,
  redeemedPoints: 0,
}

// Mock Transactions
export const MOCK_TRANSACTIONS = [
  {
    id: 'trans-1',
    userId: '1',
    merchantId: 'mcd',
    merchantName: "McDonald's Indonesia",
    amount: 150000,
    pointsEarned: 75,
    timestamp: new Date('2024-04-20'),
    items: [
      { productName: 'Big Mac Combo', quantity: 1, price: 75000 },
      { productName: 'French Fries', quantity: 2, price: 25000 },
    ],
  },
  {
    id: 'trans-2',
    userId: '1',
    merchantId: 'starbucks',
    merchantName: 'Starbucks Coffee',
    amount: 110000,
    pointsEarned: 110,
    timestamp: new Date('2024-04-18'),
    items: [{ productName: 'Caramel Macchiato', quantity: 2, price: 55000 }],
  },
  {
    id: 'trans-3',
    userId: '1',
    merchantId: 'indomaret',
    merchantName: 'Indomaret Convenience',
    amount: 100000,
    pointsEarned: 20,
    timestamp: new Date('2024-04-15'),
    items: [
      { productName: 'Snack Chitato Original', quantity: 4, price: 15000 },
      { productName: 'Aqua Botol 600ml', quantity: 8, price: 8000 },
    ],
  },
]
